### ISSUE TITLE
Mixed .jsx/.js, ES6 vs createClass

### ISSUE THREAD

**Issue by tmcw** [gatsbyjs/gatsby-starter-documentation#14]
I'm a little confused by the React & JS usage: some files, like [Breakpoint](https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/components/Breakpoint.js), have `.js` extensions and use ES6-style components & exports, whereas `_template.jsx` has a `.jsx` extension and uses `createClass` and CommonJS exports. Is this a case of slowly porting things from legacy code, or is there a reason why there are two styles in play?

**Comment by KyleAMathews** [comment]
Yeah, it's just multiple layers of architecture from different time periods that have never been cleaned up...

**Comment by tmcw** [comment]
Is now a good time in the project lifecycle to clean this up? Happy to do so, I've got some free time today, but want to make sure it won't be clobbered by a Gatsby n+1 version incoming :)

**Comment by KyleAMathews** [comment]
A PR would be great! I will be upgrading this repo in the next few weeks to
v1 but as the upgrade is mostly moving files around, your changes will
survive the journey :-)
