### ISSUE TITLE
how to make md into a React component?

### ISSUE THREAD

**Issue by jerrylau91** [gatsbyjs/gatsby-starter-documentation#8]
How can I make a md file into a React component?

**Comment by KyleAMathews** [comment]
I'm not sure I understand your question. This is exactly what Gatsby is
setup to do.

**Comment by KyleAMathews** [comment]
Can you clarify please what you're trying to understand?

**Comment by rmariuzzo** [comment]
@KyleAMathews I think you can close this. 🙂
